version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - yii-network

  webserver:
    image: nginx:alpine
    container_name: yii2-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - yii-network

  db:
    image: mariadb:10
    container_name: yii2-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test5
      MYSQL_USER: test5
      MYSQL_PASSWORD: test5privet
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - yii-network

volumes:
  dbdata:

networks:
  yii-network:
    driver: bridge